config/routes.rb
require "admin_constraint"

Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Resque::Server, at: "/jobs", constraints: AdminConstraint.new
  mount JasmineRails::Engine, at: '/specs', constraints: AdminConstraint.new if defined?(JasmineRails)

  # 1. Analytics & Charts
  # 2. Announcements
  # 3. Assignments, Submissions, Grades
  # 4. Assignment Types
  # 5. Badges
  # 6. Challenges
  # 7. Integrations
  # 8. Courses
  # 9. Groups
  # 10. Informational Pages
  # 11. Grade Schemes
  # 12. Teams
  # 13. Users
  # 14. User Auth
  # 15. Uploads
  # 16. Events
  # 17. Attendance
  # 18. API Calls
  # 19. Exports
  # 20. Learning Objectives
  # 21. Errors
  # 22. Admin

  # 1. Analytics & Charts
  namespace :analytics do
    get :staff
    get :students
    get :all_events
    get :login_events
    get :login_role_events
    get :role_events
    get :all_pageview_events
    get :all_role_pageview_events
    get :all_user_pageview_events
    get :pageview_events
    get :role_pageview_events
    get :user_pageview_events
  end

  post "analytics_events/predictor_event"
  post "analytics_events/tab_select_event"

  # 2. Announcements
  resources :announcements, except: [:edit, :update]

  # 3. Assignments, Submissions, Grades
  namespace :assignments do
    resources :importers, param: :provider_id, only: [:index, :show] do
      get :assignments
      get :download
      post "/courses/:id/assignments/import", action: :assignments_import,
        as: :assignments_import
      post "/assignments/:id/refresh", action: :refresh_assignment, as: :refresh_assignment
      post "/assignments/:id/update", action: :update_assignment, as: :update_assignment
    end
  end

  resources :assignments, except: [:create, :update]  do
    collection do
      get :feed
      get :settings
      post "copy", to: "assignments#copy"
      get "export_structure"
    end

    member do
      get "grades_review"
    end

    # routes for all grades that are associated with an assignment
    # single resources should go directly on the grades controller
    resources :grades, only: [:index], module: :assignments do
      collection do
        get :export
        get :export_earned_levels
        get :mass_edit
        put :mass_update
        post :self_log
        delete :delete_self_logged
        delete :delete_all
      end
    end

    resource :groups, only: [], module: :assignments do
      resources :grades, only: [], module: :groups do
        collection do
          get :mass_edit
          put :mass_update
        end
      end
    end

    namespace :grades do
      resources :importers, param: :provider_id, only: [:index, :show] do
        get :download
        post :upload
        get :assignments
        get "/courses/:id/grades", action: :grades, as: :grades
        post "/courses/:id/grades/import", action: :grades_import, as: :grades_import
      end
    end

    resources :groups, only: [], module: :assignments do
      get :grade, on: :member
    end

    resources :students, only: [], module: :assignments do
      post :grade
    end

    resources :submissions, except: :index

    resource :rubrics, only: :destroy do
      get :index_for_copy, on: :collection
      post :copy, on: :collection
      get :export, on: :collection
    end
  end

  resources :grades, only: [:show, :destroy, :edit] do
    member do
      post :exclude
      post :feedback_read
      post :include
    end
    collection do
      put :release
    end
  end

  resources :submission_files, only: [] do
    get :download
  end

  resources :unlock_states, only: [:create, :destroy, :update] do
    member do
      post :manually_unlock
    end
  end
  resources :unlock_conditions, only: [:create, :destroy, :update]

  resources :levels, only: [:create, :destroy, :update]

  # 4. Assignment Types
  resources :assignment_types, except: [:show] do
    get :all_grades, on: :member
    get :export_scores, on: :member
    get :export_all_scores, on: :collection
  end

  # 5. Badges
  resources :badges, except: [:update, :create] do
    get "export_structure", on: :collection
    resources :earned_badges do
      get :mass_edit, on: :collection
      post :mass_earn, on: :collection
    end
    namespace :badges do
      resources :importers, param: :provider_id, only: [:index, :show] do
        get :download
        post :upload
      end
    end
  end

  # 6. Challenges
  resources :challenges do
    resources :challenge_grades, only: [:new, :create], module: :challenges do
      collection do
        put :release
        get :mass_edit
        put :mass_update
      end
    end
  end

  resources :challenge_grades, except: [:index, :new, :create]

  # 7. Integrations
  resources :integrations, only: [:create, :index] do
    collection do
      resource :google, controller: :google, only: [], module: :integrations do
        collection do
          get :new_user
          get :confirm_instructor_role
        end
      end
    end
    resources :courses, only: [:create, :destroy], module: :integrations
  end

  namespace :google_calendars, only: [] do
    resources :assignments, only: [ ] do
      collection do
        post "assignment/:id", action: :add_assignment, as: :add_assignment
        post "/all_assignments", action: :add_assignments, as: :add_assignments
      end
    end
    resources :events do
      collection do
        post "event/:id", action: :add_event, as: :add_event
        post "/all_events", action: :add_events, as: :add_events
      end
    end
  end

  # 8. Courses
  resources :courses, except: [:show] do
    post :copy, on: :collection
    post :recalculate_student_scores, on: :member
    put :publish, on: :member
    put :unpublish, on: :member
    post :activate_all_students, on: :collection
    get :badges, on: :member
    get :change, on: :member
    get :new_external, on: :collection
    post :create_external, on: :collection
    get :overview, on: :collection
    get :edit_dashboard_message, on: :collection
    put :update_dashboard_message, on: :collection

    resources :multipliers, only: [] do
      get :export, on: :collection
    end
  end

  resources :course_memberships, only: [:index, :create, :delete, :destroy] do
    collection do
      delete :delete_many
    end
    member do
      put :deactivate
      put :reactivate
    end
  end

  # 9. Groups
  resources :groups

  # 10. Informational Pages
  controller :info do
    get :dashboard
    get :predictor
    get :earned_badges
    get :export_earned_badges
    get :final_grades
    get :gradebook
    get :learning_objectives_outcomes_file
    get :submissions
    get :grading_status
    get :gradebook_file
    get :multiplied_gradebook
    get :multiplier_choices
    get :per_assign
    get :research_gradebook
    get :syllabus
  end

  controller :home do
    get :login
    get :reset_password
    get :health_check
    get :style_guide, constraints: AdminConstraint.new
  end

  # 11. Grade Schemes
  resources :grade_scheme_elements, only: [:index, :edit, :update] do
    collection do
      get :mass_edit
      get :export_structure
    end
  end

  # 12. Teams
  resources :teams

  # 13. Users
  %w{students gsis professors admins}.each do |role|
    get "users/#{role}/new", to: "users#new", as: "new_#{role.singularize}",
      role: role.singularize
  end

  resources :users, except: :show do
    member do
      get :activate
      get :activate_set_password
      get :resend_activation_email
      put :manually_activate
      post :activate_set_password, action: :activated
      post :activate, action: :activated_external
      post :flag
    end
    collection do
      get :edit_profile
      put :update_profile
      get :import
      get :search
      post :upload
      get :new_external
      get :new_external_google
      post :create_external
    end
  end

  namespace :users do
    resources :importers, only: :index, param: :provider_id do
      get :users
      get :download
      post "/course/:id/users/import", action: :users_import, as: :users_import
    end
  end

  resources :students, only: [:index, :show] do
    resources :badges, only: [:index, :show], module: :students
    resources :assignment_type_weights, only: [:index], module: :students
    member do
      get :recalculate
    end
  end

  resources :staff, only: [:index, :show]

  resources :observers, only: :index

  # 14. User Auth
  post "auth/lti/callback", to: "user_sessions#lti_create"
  get "auth/google_oauth2/callback", to: "integrations/google#auth_callback"
  get "/auth/:provider/callback", to: "authorizations#create", as: :create_authorization
  get "auth/failure", to: "application#failed_authentication", as: :auth_failure

  # Canvas OmniAuth setup
  match "/auth/canvas/setup", to: "canvas_session#new", via: [:get, :post]

  get :logout, to: "user_sessions#destroy", as: :logout
  resources :user_sessions, only: [:create, :destroy, :student] do
    collection do
      get :instructors
    end
  end
  resources :passwords, except: [:new, :destroy, :index, :show]

  get "impersonate_student/:student_id", to: "user_sessions#impersonate_student", as: :student_preview
  get "exit_student_impersonation", to: "user_sessions#exit_student_impersonation"

  # SAML
  get "saml/init"
  post "saml/consume"
  get "saml/metadata"
  get "saml/logout"

  get "lti/:provider/launch", to: "lti#launch", as: :launch_lti_provider

  # Google Auth
  post "google/launch_from_activation_token/users/:id", to: "google#launch_from_activation_token", as: :launch_from_activation_token_google
  post "google/launch_from_login/", to: "google#launch_from_login", as: :launch_from_login_google

  # 15. Uploads
  resource :uploads, only: [] do
    get :remove
  end

  # 16. Events
  resources :events do
    post :copy, on: :collection
  end

  resources :canvas_session, only: [:index, :new]

app/models/group.rb
class Group < ApplicationRecord
  include ActiveModel::Validations
  include Sanitizable

  APPROVED_STATUSES = ["Pending", "Approved", "Rejected"]

  attr_reader :student_tokens

  belongs_to :course

  has_many :assignment_groups, dependent: :destroy, inverse_of: :group
  has_many :assignments, through: :assignment_groups
  accepts_nested_attributes_for :assignment_groups

  has_many :group_memberships, dependent: :destroy
  has_many :students, through: :group_memberships
  accepts_nested_attributes_for :group_memberships

  has_many :grades, dependent: :destroy
  has_many :proposals, dependent: :destroy
  accepts_nested_attributes_for :proposals, allow_destroy: true, reject_if: proc { |a| a["proposal"].blank? }

  has_many :submissions, dependent: :destroy
  has_many :submissions_exports

  has_many :earned_badges, as: :group

  before_validation :cache_associations

  validates_presence_of :name, :approved

  validates :group_size, group_size: true
  validates_with UniqueAssignmentPerGroupMembershipValidator, attributes: [:assignments, :group_memberships]
  validates_with AssignmentGroupPresentValidator, attributes: [:assignment_groups]

  scope :approved, -> { where approved: "Approved" }
  scope :rejected, -> { where approved: "Rejected" }
  scope :pending, -> { where approved: "Pending" }
  scope :order_by_name, -> { order "name ASC" }

  clean_html :text_proposal

  # Instructors need to approve a group before the group is allowed to proceed
  def approved?
    approved == "Approved"
  end

  def rejected?
    approved == "Rejected"
  end

  def pending?
    approved == "Pending"
  end

  def same_name_as?(another_group)
    name.downcase == another_group.name.downcase
  end

  # Group submissions
  def submission_for_assignment(assignment, submitted_only=true)
    submissions = submissions_by_assignment_id[assignment.id]
    if submissions.nil?
      nil
    else
      submitted_only ? submissions.reject(&:unsubmitted?).try(:first) : submissions.try(:first)
    end
  end

  def submitter_directory_name
    Formatter::Filename.new(name).directory_name.filename
  end

  def submitter_directory_name_with_suffix
    "#{submitter_directory_name} - #{id}"
  end

  # Grabbing the grade for an assignment
  def grade_for_assignment(assignment)
    grades.where(assignment_id: assignment.id).first || grades.new(assignment: assignment)
  end

  private

  def submissions_by_assignment_id
    @submissions_by_assignment ||= submissions.group_by(&:assignment_id)
  end

  def cache_associations
    self.course_id ||= assignments.first.try(:course_id)
  end
end

app/controllers/api/assignments/grades_controller.rb
class API::Assignments::GradesController < ApplicationController
  before_action :ensure_staff?

  # GET /api/assignments/:assignment_id/grades
  def show
    @assignment = Assignment.includes(grades: :student).find params[:assignment_id]

    if params[:team_id].present?
      team = current_course.teams.find params[:team_id]
      students = current_course.students_being_graded_by_team(team).order_by_name
    else
      students = current_course.students_being_graded.order_by_name
    end
    @grades = Gradebook.new(@assignment, students).grades
  end

  # GET /api/assignments/grades/release
  # Params: grade_ids[]
  def release
    grades = current_course.grades.where(id: params[:grade_ids])
    return head :not_found if grades.empty?

    release_grades(grades)
    head :ok
  end

  private

  def release_grades(grades)
    grades.update instructor_modified: true, complete: true, student_visible: true
    enqueue_grade_update_jobs grades.pluck(:id)
  end

  def enqueue_grade_update_jobs(grade_ids)
    grade_ids.each { |id| GradeUpdaterJob.new(grade_id: id).enqueue }
  end
end

app/controllers/api/assignments/groups/grades_controller.rb
class API::Assignments::Groups::GradesController < ApplicationController
  before_action :ensure_staff?
  before_action :ensure_group_graded!

  GradeByGroup = Struct.new(:group, :grade)

  # GET /api/assignments/:assignment_id/groups/grades
  def index
    @groups = @assignment.groups.order_by_name

    @group_grades = {}
    @groups.each { |group| @group_grades[group.id] = Gradebook.new(@assignment, group.students.order_by_name).grades }
  end

  # GET /api/assignments/:assignment_id/groups/grades/mass_edit
  #
  # Returns a very specific structure that the associated update method on the
  # controller expects
  def mass_edit
    @grades_by_group = @assignment.groups.order_by_name.map do |group|
      GradeByGroup.new(group, Gradebook.new(@assignment, group.students).grades.first)
    end
  end

  private

  def ensure_group_graded!
    @assignment = current_course.assignments.includes(:groups, :grades).find params[:assignment_id]

    render json: "Assignment is not group graded", status: :bad_request \
      if !@assignment.has_groups?
  end
end

app/controllers/api/courses/importers_controller.rb
class API::Courses::ImportersController < ApplicationController
  include OAuthProvider
  include CanvasAuthorization

  oauth_provider_param :importer_provider_id

  before_action :ensure_staff?
  before_action :link_canvas_credentials, if: Proc.new { |c| c.params[:importer_provider_id] == "canvas" }
  before_action :require_authorization

  # Retrieves all courses for the current user for a given provider
  # GET /api/courses/importers/:importer_provider_id/courses
  def index
    @provider_name = params[:importer_provider_id]
    @courses = syllabus(@provider_name).courses

    render "api/integrations/courses/index", status: 200
  end

  private

  def syllabus(provider)
    @syllabus ||= ActiveLMS::Syllabus.new \
      provider,
      authorization(provider).access_token
  end
end

app/controllers/api/grades/earned_badges_controller.rb
class API::Grades::EarnedBadgesController < ApplicationController
  # POST /api/grades/:grade_id/earned_badges
  def create
    render json: EarnedBadge.create(earned_badges_params[:earned_badges])
  end

  # DELETE /api/grades/:grade_id/earned_badges/delete_all
  def delete_all
    if !EarnedBadge.where(grade_id: params[:grade_id]).destroy_all.empty?
      render json: {
        message: "Earned badges successfully deleted", success: true
        }, status: 200
    else
      render json: {
        message: "Earned badges failed to delete", success: false
        }, status: 400
    end
  end

  private

  def earned_badges_params
    params.permit earned_badges: [:points, :feedback, :student_id,
      :badge_id, :submission_id, :course_id, :assignment_id, :level_id, :criterion_id,
      :grade_id, :student_visible, :_destroy]
  end
end

app/helpers/grades_helper.rb
module GradesHelper
  extend SubmissionsHelper

  def grading_status_count_for(course)
    ready_for_release_grades_count_for(course) +
      in_progress_grades_count_for(course) +
      ungraded_submissions_count_for(course) +
      resubmission_count_for(course)
  end

  def in_progress_grades_count_for(course)
    Rails.cache.fetch(in_progress_grades_count_cache_key(course)) do
      course.grades.for_active_students.in_progress.count
    end
  end

  def in_progress_grades_count_cache_key(course)
    # This cache key should be expired when a grade is updated
    "#{course.cache_key}/in_progress_grades_count"
  end

  def ready_for_release_grades_count_for(course)
    Rails.cache.fetch(ready_for_release_count_cache_key(course)) do
      course.grades.for_active_students.ready_for_release.count
    end
  end

  def ready_for_release_count_cache_key(course)
    # This cache key should be expired when a grade is updated
    "#{course.cache_key}/ready_for_release_grades_count"
  end

  # Returns the corresponding pass/fail status for a score
  # If the score is not a 0 or 1, the status will be nil
  def pass_fail_status_for(score)
    return status = "Pass" if score == 1
    return status = "Fail" if score == 0
    nil
  end
end

app/views/grades/importers/_import_results_table.html.haml
- term_for_score = @assignment.pass_fail? ? "Pass / Fail Status" : "Score"
%table.dynatable
  %thead
    %tr
      %th First Name
      %th Last Name
      %th Email
      %th{ "data-dynatable-sorts" => "rawScore" }= term_for_score
      %th Feedback
  %tbody
    - grades.each do |grade|
      %tr
        %td= link_to grade.student.first_name, student_path(grade.student)
        %td= link_to grade.student.last_name, student_path(grade.student)
        %td= link_to grade.student.email, student_path(grade.student)
        - if @assignment.pass_fail?
          %td
            - if grade.pass_fail_status.present?
              = term_for grade.try(:pass_fail_status)
        - else
          %td= grade.raw_points
        %td= grade.feedback

app/views/grades/importers/assignments.html.haml
.pageContent
  %canvas-assignments-selector{"provider"=>"#{@provider_name}",
                               "assignment-id"=>"#{@assignment.id}",
                               "assignment-name"=>"#{@assignment.name}"}

app/views/grades/importers/csv.html.haml
.pageContent
  = render "layouts/alerts"

  %p
    To import grades, upload a .csv file with the following format. These fields <b> MUST </b> be in the specified order. Two important keys:
    %ul
      %li You may include additional information in the extra columns, but that content will be ignored.
      %li If a student already has a grade for this assignment in GradeCraft, and there is a new grade present in the upload, <b> the old grade will be replaced. </b>

  %hr

    %p
      Columns should be in the following order:
      %br #{term_for :student}'s first name, #{term_for :student}'s last name, #{term_for :student}'s email or username, score, and any text feedback you'd like to include. #{link_to "Download Sample File", assignment_grades_importer_download_path(@assignment, :csv, format: "csv"), class: "bold"}

    = form_tag({action: :upload, importer_provider_id: params[:provider_id]}, :multipart => true) do
      = file_field_tag "file"

      .main-buttons
        = submit_tag "Import", class: "button action"

app/views/grades/importers/grades.html.haml
.pageContent
  %grade-import-form{"assignment-ids"=>"#{@assignment_ids}",
                     "current_assignment_id"=>"#{@assignment.id}",
                     "provider"=>"#{@provider_name}",
                     "course-id"=>"#{@course_id}",
                     "authenticity_token"=>"#{form_authenticity_token}",
                     "assignment_name"=>"#{@assignment.name}"}

app/views/grades/importers/grades_import_results.html.haml
.pageContent
  = render "layouts/alerts"

  - unless @result.users_import_result.unsuccessful.empty?
    .table-header-information
      %h4.subtitle
        = "#{@result.users_import_result.unsuccessful.count} #{term_for(:student).pluralize(@result.users_import_result.unsuccessful.count)} Not Imported"
      %table.dynatable
        %thead
          %tr
            %th Data
            %th Error(s)
        %tbody
          - @result.users_import_result.unsuccessful.each do |row|
            %tr
              %td= row[:data]
              %td= row[:errors]

  .table-header-information
    %h4.subtitle
      = "#{@result.users_import_result.successful.count} #{term_for(:student).pluralize(@result.users_import_result.successful.count)} Imported Successfully"
    %table.dynatable
      %thead
        %tr
          %th First Name
          %th Last Name
          %th Username
          %th Email
      %tbody
        - @result.users_import_result.successful.each do |user|
          %tr
            %td= link_to user.first_name, student_path(user)
            %td= link_to user.last_name, student_path(user)
            %td= link_to user.username, student_path(user)
            %td= link_to user.email, student_path(user)

  - unless @result.grades_import_result.unsuccessful.empty?
    .table-header-information
      %h4.subtitle
        = "#{@result.grades_import_result.unsuccessful.count} #{"Grade".pluralize(@result.grades_import_result.unsuccessful.count)} Not Imported into #{@assignment.name}"
      %table.dynatable
        %thead
          %tr
            %th User
            %th Error(s)
        %tbody
          - @result.grades_import_result.unsuccessful.each do |row|
            %tr
              %td
                = row[:data]["user"]["name"]
              %td= row[:errors]

  .table-header-information
    %h4.subtitle
      = "#{@result.grades_import_result.successful.count} #{"Grade".pluralize(@result.grades_import_result.successful.count)} Imported Successfully into #{@assignment.name}"
    %table.dynatable
      %thead
        %tr
          %th First Name
          %th Last Name
          %th Raw Points
          %th Score
          %th Feedback
      %tbody
        - @result.grades_import_result.successful.each do |grade|
          %tr
            %td= grade.student.first_name
            %td= grade.student.last_name
            %td= points grade.raw_points
            %td= grade.score
            %td= grade.feedback

app/views/grades/importers/import_results.html.haml
.pageContent
  = render "layouts/alerts"

  - unless @result.unsuccessful.empty?
    %h2.subtitle
      = "#{@result.unsuccessful.count} #{"Grade".pluralize(@result.unsuccessful.count)} Not Imported"
    %table.dynatable
      %thead
        %tr
          %th Data
          %th Error(s)
      %tbody
        - @result.unsuccessful.each do |row|
          %tr
            %td= row[:data]
            %td= row[:errors]

  %h2.subtitle
    = "#{@result.successful.count} #{"Grade".pluralize(@result.successful.count)} Imported Successfully"
  = render partial: "grades/importers/import_results_table", locals: { grades: @result.successful }

  - unless @result.unchanged.empty?
    %h2.subtitle
      = "#{@result.unchanged.count} #{"Grade".pluralize(@result.unchanged.count)} Not Imported (already existed)"
    = render partial: "grades/importers/import_results_table", locals: { grades: @result.unchanged }

app/views/grades/importers/index.html.haml
.pageContent
  = render partial: "layouts/alerts"

  %section
    .card.left{style: "height: 400px;"}
      .card-cap
        = image_tag "csv-logo.png", height: "46px"
      .card-block
        %h4.card-title CSV
        .card-text
        %p.card-text
          Upload a .csv file with grade information for students to import the student grades.

        = link_to "Import Grades from CSV", assignment_grades_importer_path(@assignment, :csv), class: "card-link button"

    - if current_course.allows_canvas?
      .card.left{style: "height: 400px;"}
        .card-cap
          = image_tag "canvas-logo.png", height: "46px"
        .card-block
          %h4.card-title Canvas LMS
          .card-text
          %p.card-text
            An open-source LMS from Instructure. Import any grade for the courses you are enrolled as a teacher.

          = link_to "Import Canvas Grades", assignment_grades_importer_assignments_path(@assignment, :canvas), class: "card-link button"