config/routes.rb
require "admin_constraint"

Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Resque::Server, at: "/jobs", constraints: AdminConstraint.new
  mount JasmineRails::Engine, at: '/specs', constraints: AdminConstraint.new if defined?(JasmineRails)

  # 1. Analytics & Charts
  # 2. Announcements
  # 3. Assignments, Submissions, Grades
  # 4. Assignment Types
  # 5. Badges
  # 6. Challenges
  # 7. Integrations
  # 8. Courses
  # 9. Groups
  # 10. Informational Pages
  # 11. Grade Schemes
  # 12. Teams
  # 13. Users
  # 14. User Auth
  # 15. Uploads
  # 16. Events
  # 17. Attendance
  # 18. API Calls
  # 19. Exports
  # 20. Learning Objectives
  # 21. Errors
  # 22. Admin

  # 1. Analytics & Charts
  namespace :analytics do
    get :staff
    get :students
    get :all_events
    get :login_events
    get :login_role_events
    get :role_events
    get :all_pageview_events
    get :all_role_pageview_events
    get :all_user_pageview_events
    get :pageview_events
    get :role_pageview_events
    get :user_pageview_events
  end

  post "analytics_events/predictor_event"
  post "analytics_events/tab_select_event"

  # 2. Announcements
  resources :announcements, except: [:edit, :update]

  # 3. Assignments, Submissions, Grades
  namespace :assignments do
    resources :importers, param: :provider_id, only: [:index, :show] do
      get :assignments
      get :download
      post "/courses/:id/assignments/import", action: :assignments_import,
        as: :assignments_import
      post "/assignments/:id/refresh", action: :refresh_assignment, as: :refresh_assignment
      post "/assignments/:id/update", action: :update_assignment, as: :update_assignment
    end
  end

  resources :assignments, except: [:create, :update]  do
    collection do
      get :feed
      get :settings
      post "copy", to: "assignments#copy"
      get "export_structure"
    end

    member do
      get "grades_review"
    end

    # routes for all grades that are associated with an assignment
    # single resources should go directly on the grades controller
    resources :grades, only: [:index], module: :assignments do
      collection do
        get :export
        get :export_earned_levels
        get :mass_edit
        put :mass_update
        post :self_log
        delete :delete_self_logged
        delete :delete_all
      end
    end

    resource :groups, only: [], module: :assignments do
      resources :grades, only: [], module: :groups do
        collection do
          get :mass_edit
          put :mass_update
        end
      end
    end

    namespace :grades do
      resources :importers, param: :provider_id, only: [:index, :show] do
        get :download
        post :upload
        get :assignments
        get "/courses/:id/grades", action: :grades, as: :grades
        post "/courses/:id/grades/import", action: :grades_import, as: :grades_import
      end
    end

    resources :groups, only: [], module: :assignments do
      get :grade, on: :member
    end

    resources :students, only: [], module: :assignments do
      post :grade
    end

    resources :submissions, except: :index

    resource :rubrics, only: :destroy do
      get :index_for_copy, on: :collection
      post :copy, on: :collection
      get :export, on: :collection
    end
  end

  resources :grades, only: [:show, :destroy, :edit] do
    member do
      post :exclude
      post :feedback_read
      post :include
    end
    collection do
      put :release
    end
  end

  resources :submission_files, only: [] do
    get :download
  end

  resources :unlock_states, only: [:create, :destroy, :update] do
    member do
      post :manually_unlock
    end
  end
  resources :unlock_conditions, only: [:create, :destroy, :update]

  resources :levels, only: [:create, :destroy, :update]

  # 4. Assignment Types
  resources :assignment_types, except: [:show] do
    get :all_grades, on: :member
    get :export_scores, on: :member
    get :export_all_scores, on: :collection
  end

  # 5. Badges
  resources :badges, except: [:update, :create] do
    get "export_structure", on: :collection
    resources :earned_badges do
      get :mass_edit, on: :collection
      post :mass_earn, on: :collection
    end
    namespace :badges do
      resources :importers, param: :provider_id, only: [:index, :show] do
        get :download
        post :upload
      end
    end
  end

  # 6. Challenges
  resources :challenges do
    resources :challenge_grades, only: [:new, :create], module: :challenges do
      collection do
        put :release
        get :mass_edit
        put :mass_update
      end
    end
  end

  resources :challenge_grades, except: [:index, :new, :create]

  # 7. Integrations
  resources :integrations, only: [:create, :index] do
    collection do
      resource :google, controller: :google, only: [], module: :integrations do
        collection do
          get :new_user
          get :confirm_instructor_role
        end
      end
    end
    resources :courses, only: [:create, :destroy], module: :integrations
  end

  namespace :google_calendars, only: [] do
    resources :assignments, only: [ ] do
      collection do
        post "assignment/:id", action: :add_assignment, as: :add_assignment
        post "/all_assignments", action: :add_assignments, as: :add_assignments
      end
    end
    resources :events do
      collection do
        post "event/:id", action: :add_event, as: :add_event
        post "/all_events", action: :add_events, as: :add_events
      end
    end
  end

  # 8. Courses
  resources :courses, except: [:show] do
    post :copy, on: :collection
    post :recalculate_student_scores, on: :member
    put :publish, on: :member
    put :unpublish, on: :member
    post :activate_all_students, on: :collection
    get :badges, on: :member
    get :change, on: :member
    get :new_external, on: :collection
    post :create_external, on: :collection
    get :overview, on: :collection
    get :edit_dashboard_message, on: :collection
    put :update_dashboard_message, on: :collection

    resources :multipliers, only: [] do
      get :export, on: :collection
    end
  end

  resources :course_memberships, only: [:index, :create, :delete, :destroy] do
    collection do
      delete :delete_many
    end
    member do
      put :deactivate
      put :reactivate
    end
  end

  # 9. Groups
  resources :groups

  # 10. Informational Pages
  controller :info do
    get :dashboard
    get :predictor
    get :earned_badges
    get :export_earned_badges
    get :final_grades
    get :gradebook
    get :learning_objectives_outcomes_file
    get :submissions
    get :grading_status
    get :gradebook_file
    get :multiplied_gradebook
    get :multiplier_choices
    get :per_assign
    get :research_gradebook
    get :syllabus
  end

  controller :home do
    get :login
    get :reset_password
    get :health_check
    get :style_guide, constraints: AdminConstraint.new
  end

  # 11. Grade Schemes
  resources :grade_scheme_elements, only: [:index, :edit, :update] do
    collection do
      get :mass_edit
      get :export_structure
    end
  end

  # 12. Teams
  resources :teams

  # 13. Users
  %w{students gsis professors admins}.each do |role|
    get "users/#{role}/new", to: "users#new", as: "new_#{role.singularize}",
      role: role.singularize
  end

  resources :users, except: :show do
    member do
      get :activate
      get :activate_set_password
      get :resend_activation_email
      put :manually_activate
      post :activate_set_password, action: :activated
      post :activate, action: :activated_external
      post :flag
    end
    collection do
      get :edit_profile
      put :update_profile
      get :import
      get :search
      post :upload
      get :new_external
      get :new_external_google
      post :create_external
    end
  end

  namespace :users do
    resources :importers, only: :index, param: :provider_id do
      get :users
      get :download
      post "/course/:id/users/import", action: :users_import, as: :users_import
    end
  end

  resources :students, only: [:index, :show] do
    resources :badges, only: [:index, :show], module: :students
    resources :assignment_type_weights, only: [:index], module: :students
    member do
      get :recalculate
    end
  end

  resources :staff, only: [:index, :show]

  resources :observers, only: :index

  # 14. User Auth
  post "auth/lti/callback", to: "user_sessions#lti_create"
  get "auth/google_oauth2/callback", to: "integrations/google#auth_callback"
  get "/auth/:provider/callback", to: "authorizations#create", as: :create_authorization
  get "auth/failure", to: "application#failed_authentication", as: :auth_failure

  # Canvas OmniAuth setup
  match "/auth/canvas/setup", to: "canvas_session#new", via: [:get, :post]

  get :logout, to: "user_sessions#destroy", as: :logout
  resources :user_sessions, only: [:create, :destroy, :student] do
    collection do
      get :instructors
    end
  end
  resources :passwords, except: [:new, :destroy, :index, :show]

  get "impersonate_student/:student_id", to: "user_sessions#impersonate_student", as: :student_preview
  get "exit_student_impersonation", to: "user_sessions#exit_student_impersonation"

  # SAML
  get "saml/init"
  post "saml/consume"
  get "saml/metadata"
  get "saml/logout"

  get "lti/:provider/launch", to: "lti#launch", as: :launch_lti_provider

  # Google Auth
  post "google/launch_from_activation_token/users/:id", to: "google#launch_from_activation_token", as: :launch_from_activation_token_google
  post "google/launch_from_login/", to: "google#launch_from_login", as: :launch_from_login_google

  # 15. Uploads
  resource :uploads, only: [] do
    get :remove
  end

  # 16. Events
  resources :events do
    post :copy, on: :collection
  end

  resources :canvas_session, only: [:index, :new]

app/controllers/api/assignments/groups/grades_controller.rb
class API::Assignments::Groups::GradesController < ApplicationController
  before_action :ensure_staff?
  before_action :ensure_group_graded!

  GradeByGroup = Struct.new(:group, :grade)

  # GET /api/assignments/:assignment_id/groups/grades
  def index
    @groups = @assignment.groups.order_by_name

    @group_grades = {}
    @groups.each { |group| @group_grades[group.id] = Gradebook.new(@assignment, group.students.order_by_name).grades }
  end

  # GET /api/assignments/:assignment_id/groups/grades/mass_edit
  #
  # Returns a very specific structure that the associated update method on the
  # controller expects
  def mass_edit
    @grades_by_group = @assignment.groups.order_by_name.map do |group|
      GradeByGroup.new(group, Gradebook.new(@assignment, group.students).grades.first)
    end
  end

  private

  def ensure_group_graded!
    @assignment = current_course.assignments.includes(:groups, :grades).find params[:assignment_id]

    render json: "Assignment is not group graded", status: :bad_request \
      if !@assignment.has_groups?
  end
end

app/controllers/assignments/groups/grades_controller.rb
require_relative "../../../services/creates_many_group_grades"

class Assignments::Groups::GradesController < ApplicationController
  before_action :ensure_staff?
  before_action :find_assignment
  before_action :use_current_course

  # GET /assignments/:assignment_id/groups/grades/mass_edit
  def mass_edit
  end

  # PUT /assignments/:assignment_id/groups/grades/mass_update
  def mass_update
    filter_params_with_no_grades!
    params[:assignment][:grades_by_group] = assignment_group_grades_params[:grades_by_group].each do |key, value|
      value.merge!(instructor_modified: true, complete: true, student_visible: true)
    end

    result = Services::CreatesManyGroupGrades.call @assignment.id,
      current_user.id,
      assignment_group_grades_params

    if result.success?
      respond_with @assignment
    else
      redirect_to mass_edit_assignment_groups_grades_path(@assignment),
        notice: "Oops! There was an error while saving the grades!"
    end
  end
end

private

def assignment_group_grades_params
  params.require(:assignment).permit grades_by_group: [:graded_by_id, :graded_at,
    :instructor_modified, :raw_points, :pass_fail_status, :group_id, :complete, :student_visible]
end

def find_assignment
  @assignment = current_course.assignments.find(params[:assignment_id])
end

def filter_params_with_no_grades!
  params[:assignment][:grades_by_group].delete_if do |key, value|
    value[:raw_points].blank? && (value[:pass_fail_status].blank? || value[:pass_fail_status] == "nil")
  end
end

app/controllers/assignments/groups_controller.rb
class Assignments::GroupsController < ApplicationController
  before_action :ensure_staff?
  before_action :use_current_course

  # GET /assignments/:assignment_id/groups/:id/grade
  # Grading an assignment for a group
  def grade
    @assignment = current_course.assignments.find(params[:assignment_id])
    @group = @assignment.groups.find(params[:id])
    @submission = @assignment.submissions.where(group_id: @group.id).first
    @assignment_score_levels = @assignment.assignment_score_levels.order_by_points
    @grade_next_path = path_for_next_group_grade @assignment, @group
    @rubric = @assignment.rubric if @assignment.grade_with_rubric?

    grades = Grade.find_or_create_grades(@assignment.id, @group.students.pluck(:id))
    grades.update_all(complete: false, student_visible: false)
  end

  private

  def path_for_next_group_grade(assignment, group)
    # we don't supply grade next buttons when editing a student visible grade
    return nil if group.grade_for_assignment(assignment).student_visible?
    next_group = assignment.next_ungraded_group(group)
    return assignment_path(assignment) unless next_group.present?
    return grade_assignment_group_path(assignment_id: assignment.id, id: next_group.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_staff?, only: [:index, :destroy]

  before_action :find_group, only: [:show, :edit, :update, :destroy]
  before_action :find_group_assignments, only: [:new, :edit, :create, :update]
  before_action :use_current_course

  def index
    groups = @course.groups.includes(assignment_groups: :assignment, group_memberships: :student)
    @pending_groups = groups.pending
    @approved_groups = groups.approved
    @rejected_groups = groups.rejected
    @assignments = @course.assignments.includes(:assignment_groups).group_assignments
  end

  def show
  end

  def new
    @group = @course.groups.new
    @other_students = potential_team_members
  end

  def create
    @group = @course.groups.new(group_params)
    @group.students << current_student if current_user_is_student?
    if current_user_is_student?
      @group.approved = "Pending"
    else
      @group.approved = "Approved"
    end
    respond_to do |format|
      if @group.save
        @group.students.each do |group_member|
          NotificationMailer.group_notify(group_member, @group).deliver_later
        end

        format.html { respond_with @group }
      else
        @other_students = potential_team_members
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @other_students = potential_team_members
  end

  def update
    respond_to do |format|
      if @group.update_attributes(group_params)
        @group.students.each do |group_member|
          NotificationMailer.group_status_updated(group_member, @group).deliver_later
        end

        format.html { respond_with @group }
      else
        @other_students = potential_team_members
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_path }
      flash[:success]= "#{@group.name} #{term_for :group} successfully deleted"
    end
  end

  private

  def group_params
    params.require(:group).permit :name, :approved, :course_id,
      proposals_attributes: [:approved, :title, :group_id, :submitted_by, :feedback, :proposal, :id],
      assignment_groups_attributes: [:assignment_id, :group_id, :id],
      group_membership_attributes: [:accepted, :group_id, :student_id, :id, :course_id],
      assignment_ids: [], student_ids: []
  end
  
  def potential_team_members
    current_course.students.where.not(id: current_user.id).order_by_name
  end

  def find_group
    @group = current_course.groups.includes(:proposals).find(params[:id])
  end

  def find_group_assignments
    @group_assignments = current_course.assignments.group_assignments
  end

end

app/views/groups/_buttons.haml
- content_for :context_menu do
  .context-menu
    %ul
      = active_course_link_to decorative_glyph(:plus) + "New #{term_for :group}", new_group_path, class: "button button-edit"

app/views/groups/_form.html.haml
= simple_form_for @group do |f|

  = render partial: "layouts/alerts", locals: { model: @group }

  %section.form-section
    - if @group.pending? && current_user_is_staff?
      = f.label :approved, "Status"
      = f.select :approved, [["Pending"], ["Approved"], ["Rejected"]]
      .form-hint If rejected, this #{term_for :group} will be unable to submit any further work for these assignments

      %hr.dotted

    .form-item
      = f.input :name, :label => "#{term_for :group} Name"

    .form-item
      = f.association :assignments, :collection => @group_assignments, as: :check_boxes, :label => "#{(term_for :assignments).titleize}"
      .form-hint{id: "txtGroupAssignment"} What #{term_for :assignments} will this #{term_for :group} work on together?

    - if current_user_is_student? && !@group.persisted?
      .form-item
        = f.association :students, :collection => @other_students, as: :select, :label => "#{term_for :students}"
        .form-hint= "You (#{current_student.name }) will be automatically included in this group."
    - elsif current_user_is_student?
      .form-item= f.association :students, :collection => current_course.students.order_by_name, as: :select, :label => "#{term_for :students}"
    - if current_user_is_staff?
      .form-item= f.association :students, :collection => current_course.students.order_by_name, as: :select, :label => "#{term_for :students}"
    .form-hint{id: "txtStudentName"} Enter a fellow student's name to add them to this #{term_for :group}. Only one student needs to create the #{term_for :group}, after which all #{term_for :group} members will be able to submit work, see submitted materials, and see instructor grades and feedback.

  = render partial: "groups/proposal_section", locals: { f: f }

  %p

  .main-buttons
    = submit_tag "#{@group.persisted? ? 'Update' : 'Create'} #{ term_for :group } ",  class: "button action"
    = link_to glyph("times-circle") + "Cancel", groups_path, class: "button secondary"

app/views/groups/_groups_table.haml
%table.dynatable
  %caption.sr-only= #{term_for :groups}
  %thead
    %tr
      %th{:width => "20%"} #{term_for :group} Name
      %th{:style => "min-width: 200px"}= "#{current_course.student_term}s"
      %th{:width => "10%"} Status
      %th{:style => "min-width: 200px"} #{term_for :assignments}
      %th.options{"data-dynatable-no-sort": "true"} Options
  %tbody
    - groups.each do |group|
      %tr
        %td= link_to group.try(:name), group_path(group)
        %td
          - group.group_memberships.each do |gm|
            %li= link_to gm.student.name, student_path(gm.student)
        %td= group.approved
        %td
          - group.assignment_groups.each do |ag|
            %li= link_to ag.assignment.try(:name), ag.try(:assignment)
        %td
          .button-container.dropdown.right
            %button.button-edit.button-options{role: "button", type: "button", "aria-label": "Additional Options"}= decorative_glyph(:cog) + decorative_glyph("caret-down")
            %ul.options-menu.dropdown-content
              - if group.pending?
                = active_course_link_to decorative_glyph(:eye) + "Review #{term_for :group}", edit_group_path(id: group)
              - else
                = active_course_link_to decorative_glyph(:edit) + "Edit #{term_for :group}", edit_group_path(id: group)
              = active_course_link_to decorative_glyph(:trash) + "Delete", group_path(group), data: { confirm: "This will delete the #{group.name} #{term_for :group}, along with their submissions and grades if they have any - are you sure?" }, :method => :delete

app/views/groups/_proposal_display.haml
- i = 1
- @group.proposals.order_by_creation_date.each do |proposal|
  %fieldset.proposal.panel
    %span.columns
      %h4.bold= "Proposal ##{i}: #{proposal.title}"
      %h6= "Created: #{l proposal.created_at.in_time_zone(current_user.time_zone)}"
      %p= raw proposal.proposal
      - i += 1
  %hr.dotted

app/views/groups/_proposal_fields.html.haml
%script(id="proposal-template" type="text/x-template")
  %fieldset.proposal.callout.panel
    .form-hint= "What is your #{term_for :group} planning to do for this #{term_for :assignment}?"
    = f.simple_fields_for :proposals, Proposal.new, class: "form-inline", child_index: "child_index" do |f|
      %section
      .form-item
        = f.label :title, "Title"
        = f.text_field :title
      .textarea
        = f.label :proposal
        = f.text_area :proposal, class: "froala"
        = f.hidden_field :id

app/views/groups/_proposal_section.haml
%section
  .proposals
    = render partial: "proposal_fields", locals: { f: f }
    = render partial: "groups/proposal_display", locals: { group: @group } if @group.persisted?

    %button{role: "button", type: "button", class: "add-proposal button"} Add a Proposal

app/views/groups/_status_display.haml
- if @group.approved?
  .alert-box.success
    %i.fa.fa-check.fa-fw
    %span.bold Status: Approved
- elsif @group.rejected?
  .alert-box.alert
    %i.fa.fa-times-circle.fa-fw
    %span.bold Status: Rejected
- else
  .alert-box.notice
    %i.fa.fa-flag.fa-fw
    %span.bold Status: Pending
    This #{term_for :group} must be approved by your instructor before you can proceed

app/views/groups/edit.html.haml
- if current_user_is_staff?
  = render partial: "groups/buttons"

.pageContent
  = render partial: "groups/form"

app/views/groups/index.html.haml
= render partial: "groups/buttons"

.pageContent
  = render partial: "layouts/alerts"

  - if @pending_groups.present?
    .bg-green_lime{:style =>  "margin: 0 -1rem; padding: 1em 1em 2em 1em"}
      %h2= "Pending #{term_for :groups}"

      = render partial: "groups/groups_table", locals: { course: current_course, :groups => @pending_groups }

  - if @rejected_groups.present?

    %h2.fail= "Rejected #{term_for :groups}"

    = render partial: "groups/groups_table", locals: { course: current_course, :groups => @rejected_groups }

  - if @approved_groups.present?

    %h2= "Approved #{term_for :groups}"

    = render partial: "groups/groups_table", locals: { course: current_course, :groups => @approved_groups }

app/views/groups/new.html.haml
.pageContent
  = render partial: "groups/form"

app/views/groups/show.html.haml
- if current_user_is_staff?
  = render partial: "groups/buttons"

.pageContent
  = render partial: "layouts/alerts"

  = render partial: "status_display", locals: { group: @group }

  %h4
    Members:
  %ul
    - @group.group_memberships.each do |gm|
      - if current_user_is_staff?
        %li= link_to gm.student.name, student_path(gm.student)
      - else
        %li= gm.student.name

  %h4 #{term_for :assignments}:
  %ul
    - @group.assignment_groups.each do |ag|
      %li= link_to ag.assignment.name, ag.assignment

  - if @group.text_feedback?
    %h4 Instructor Feedback:
    %p= raw @group.try(:text_feedback)

  - if @group.proposals.present?
    = render partial: "groups/proposal_display", locals: { group: @group }