config/routes.rb
  resources :submission_files, only: [] do
    get :download
  end

  resources :unlock_states, only: [:create, :destroy, :update] do
    member do
      post :manually_unlock
    end
  end
  resources :unlock_conditions, only: [:create, :destroy, :update]

  resources :levels, only: [:create, :destroy, :update]

  # 4. Assignment Types
  resources :assignment_types, except: [:show] do
    get :all_grades, on: :member
    get :export_scores, on: :member
    get :export_all_scores, on: :collection
  end

  # 5. Badges
  resources :badges, except: [:update, :create] do
    get "export_structure", on: :collection
    resources :earned_badges do
      get :mass_edit, on: :collection
      post :mass_earn, on: :collection
    end
    namespace :badges do
      resources :importers, param: :provider_id, only: [:index, :show] do
        get :download
        post :upload
      end
    end
  end

  # 6. Challenges
  resources :challenges do
    resources :challenge_grades, only: [:new, :create], module: :challenges do
      collection do
        put :release
        get :mass_edit
        put :mass_update
      end
    end
  end

  resources :challenge_grades, except: [:index, :new, :create]

  # 7. Integrations
  resources :integrations, only: [:create, :index] do
    collection do
      resource :google, controller: :google, only: [], module: :integrations do
        collection do
          get :new_user
          get :confirm_instructor_role
        end
      end
    end
    resources :courses, only: [:create, :destroy], module: :integrations
  end

  namespace :google_calendars, only: [] do
    resources :assignments, only: [ ] do
      collection do
        post "assignment/:id", action: :add_assignment, as: :add_assignment
        post "/all_assignments", action: :add_assignments, as: :add_assignments
      end
    end
    resources :events do
      collection do
        post "event/:id", action: :add_event, as: :add_event
        post "/all_events", action: :add_events, as: :add_events
      end
    end
  end

  # 8. Courses
  resources :courses, except: [:show] do
    post :copy, on: :collection
    post :recalculate_student_scores, on: :member
    put :publish, on: :member
    put :unpublish, on: :member
    post :activate_all_students, on: :collection
    get :badges, on: :member
    get :change, on: :member
    get :new_external, on: :collection
    post :create_external, on: :collection
    get :overview, on: :collection
    get :edit_dashboard_message, on: :collection
    put :update_dashboard_message, on: :collection

    resources :multipliers, only: [] do
      get :export, on: :collection
    end
  end

  resources :course_memberships, only: [:index, :create, :delete, :destroy] do
    collection do
      delete :delete_many
    end
    member do
      put :deactivate
      put :reactivate
    end
  end

  # 9. Groups
  resources :groups

  # 10. Informational Pages
  controller :info do
    get :dashboard
    get :predictor
    get :earned_badges
    get :export_earned_badges
    get :final_grades
    get :gradebook
    get :learning_objectives_outcomes_file
    get :submissions
    get :grading_status
    get :gradebook_file
    get :multiplied_gradebook
    get :multiplier_choices
    get :per_assign
    get :research_gradebook
    get :syllabus
  end

  controller :home do
    get :login
    get :reset_password
    get :health_check
    get :style_guide, constraints: AdminConstraint.new
  end

  # 11. Grade Schemes
  resources :grade_scheme_elements, only: [:index, :edit, :update] do
    collection do
      get :mass_edit
      get :export_structure
    end
  end

  # 12. Teams
  resources :teams

  # 13. Users
  %w{students gsis professors admins}.each do |role|
    get "users/#{role}/new", to: "users#new", as: "new_#{role.singularize}",
      role: role.singularize
  end

  resources :users, except: :show do
    member do
      get :activate
      get :activate_set_password
      get :resend_activation_email
      put :manually_activate
      post :activate_set_password, action: :activated
      post :activate, action: :activated_external
      post :flag
    end
    collection do
      get :edit_profile
      put :update_profile
      get :import
      get :search
      post :upload
      get :new_external
      get :new_external_google
      post :create_external
    end
  end

  namespace :users do
    resources :importers, only: :index, param: :provider_id do
      get :users
      get :download
      post "/course/:id/users/import", action: :users_import, as: :users_import
    end
  end

  resources :students, only: [:index, :show] do
    resources :badges, only: [:index, :show], module: :students
    resources :assignment_type_weights, only: [:index], module: :students
    member do
      get :recalculate
    end
  end

  resources :staff, only: [:index, :show]

  resources :observers, only: :index

  # 14. User Auth
  post "auth/lti/callback", to: "user_sessions#lti_create"
  get "auth/google_oauth2/callback", to: "integrations/google#auth_callback"
  get "/auth/:provider/callback", to: "authorizations#create", as: :create_authorization
  get "auth/failure", to: "application#failed_authentication", as: :auth_failure

  # Canvas OmniAuth setup
  match "/auth/canvas/setup", to: "canvas_session#new", via: [:get, :post]

  get :logout, to: "user_sessions#destroy", as: :logout
  resources :user_sessions, only: [:create, :destroy, :student] do
    collection do
      get :instructors
    end
  end
  resources :passwords, except: [:new, :destroy, :index, :show]

  get "impersonate_student/:student_id", to: "user_sessions#impersonate_student", as: :student_preview
  get "exit_student_impersonation", to: "user_sessions#exit_student_impersonation"

  # SAML
  get "saml/init"
  post "saml/consume"
  get "saml/metadata"
  get "saml/logout"

  get "lti/:provider/launch", to: "lti#launch", as: :launch_lti_provider

  # Google Auth
  post "google/launch_from_activation_token/users/:id", to: "google#launch_from_activation_token", as: :launch_from_activation_token_google
  post "google/launch_from_login/", to: "google#launch_from_login", as: :launch_from_login_google

  # 15. Uploads
  resource :uploads, only: [] do
    get :remove
  end

  # 16. Events
  resources :events do
    post :copy, on: :collection
  end

  resources :canvas_session, only: [:index, :new]

  resources :institutions, only: [:index, :new, :edit, :create, :update]

  # 17. Attendance
  resources :attendance, only: [:index, :new, :create] do
    collection do
      get :setup
      get :mass_edit
    end
  end

  # 18. API Calls
  namespace :api, defaults: { format: :json } do
    resource :assignments, only: [], module: :assignments do
      resources :grades, only: [] do
        put :release, on: :collection
      end
    end
    resources :assignments, only: [], module: :assignments do
      resources :students, only: [:index]
    end

    resources :assignments, only: [:index, :show, :update, :create] do
      get "analytics"
      post :sort, on: :collection
      resources :criteria, only: :index
      resources :students, only: [] do
        resources :criteria, only: [] do
          member do
            put :update_fields, to: 'criterion_grades#update_fields'
          end
        end
        resources :criterion_grades, only: :index
        get "grade", to: 'grades#show'
        put "criterion_grades", to: "criterion_grades#update"
        resources :learning_objectives, only: [], module: :learning_objectives do
          put :update_outcome, to: "outcomes#update_outcome"
        end
      end
      resource :learning_objectives, only: [], module: :learning_objectives do
        get :outcomes, to: "outcomes#outcomes_for_assignment"
      end
      resources :grades, only: [], module: :assignments do
        get :show, on: :collection
      end
      resource :groups, only: [], module: :assignments do
        resources :grades, only: :index, module: :groups do
          get :mass_edit, on: :collection
        end
      end
      resources :groups, only: [] do
        resources :criteria, only: [] do
          member do
            put :update_fields, to: 'criterion_grades#group_update_fields'
          end
        end
        resources :learning_objectives, only: [], module: :learning_objectives do
          put :update_outcome, to: "outcomes#group_update_outcome"
        end
        get 'grades', to: 'grades#group_index'
        get 'criterion_grades', to: 'criterion_grades#group_index'
      end
      resources :submissions, only: [:create, :update], module: :assignments do
        get :show, on: :collection
      end
      resources :unlock_conditions, only: :index

      namespace :grades do
        resources :importers, only: [], param: :provider_id do
          get "/course/:id", action: :show, as: :grades
        end
      end

      collection do
        resources :importers, only: [], param: :provider_id, module: :assignments do
          get "/course/:id/assignments", action: :index, as: :assignments
          post :upload
          post :import
        end
      end
    end

    resources :assignment_types, only: [:index, :show] do
      resources :assignment_type_weights, only: :create
      post :sort, on: :collection
    end

    resources :badges, only: [:index, :show, :update, :create] do
      post :sort, on: :collection
      resources :unlock_conditions, only: :index
    end

    resources :challenges, only: :index

    resources :courses, only: [:index, :show] do
      resource :copy_log, only: [:show]
      resources :students, only: :index, module: :courses
      collection do
        get :search
        get "analytics"
        get "one_week_analytics", to: "courses#one_week_analytics"
        resources :importers, only: [], module: :courses, param: :provider_id do
          get "courses", action: :index
        end
      end
      resources :teams, only: :index, module: :courses
    end

app/controllers/home_controller.rb
require "mongoid"

# rubocop:disable AndOr
class HomeController < ApplicationController
  skip_before_action :require_login
  skip_before_action :require_course_membership
  before_action :ensure_admin?, only: :health_check
  before_action :redirect_if_logged_in!, only: [:index, :login]

  layout "blank", only: :style_guide

  # root
  # GET /
  def index
  end

  def login
  end

  def reset_password
  end

  def style_guide
  end

  def health_check
    begin
      @mongo_status = Mongoid.default_client.command(ping: 1).documents.first == {"ok"=>1.0} ? "Connected" : "Error"
      @redis_status = Resque.redis.redis.call("ping") == "PONG" ? "Connected" : "Error"
    rescue StandardError => e
      @error = e.message
      raise
    end
  end

  private

  def redirect_if_logged_in!
    redirect_to dashboard_path and return if logged_in?
  end
end

app/views/home/_public.html.haml
= link_to 'https://gradecraft.com/', class: "logo" do
  = image_tag "logo.svg", alt: "Return to GradeCraft homepage", width: "450", height: "100"

%h1 Log In
.google_access
  = link_to "Log in with Google", "/auth/google_oauth2/", tabindex: "0"

%h3 Or:
= form_for User.new, url: user_sessions_path do |f|
  .form_elem
    = f.text_field :email, placeholder: "Your email address", autocorrect: "off", autocapitalize: "off", required: "true"
    = label_tag :user_email, "Email address"
  .form_elem
    = f.password_field :password, placeholder: "Your password", required: "true"
    = label_tag :user_password, "Password"
  = f.button "Log in", type: "submit", class: "action", alt: "Log in:", style: "margin-bottom: 1em;"
%p
  = link_to "Forgot your password?", reset_password_path

- if !Rails.env.production?
  %h3{style: "margin-top: 3em;"} No account?
  %p{style: "margin-bottom: 2em;"}
    No worries!
    = link_to 'Sign up for GradeCraft', 'https://gradecraft.com/sign_up/'
    to get started!

app/views/home/_umich.html.haml
= link_to 'https://gradecraft.com/', :class => "logo" do
  = image_tag "logo.svg", :alt => "Return to GradeCraft homepage", :width => "450", :height => "100"
%h1 U-M Log in
%p If you are able to login with University of Michigan credentials, please continue:

%a.button.action{"aria-label": "University of Michigan Login", href: saml_init_path }
  Log in with U-M access
%p
  Otherwise, please
  %a{:href => 'https://gradecraft.com/'} return to the GradeCraft homepage
= image_tag "University_of_Michigan_seal.png", width: "200px", height: "200px", class: "um-seal"

app/views/home/health_check.html.haml
.pageContent
  %p= "MongoDB status: #{@mongo_status}"
  %p= "Redis status: #{@redis_status}"

  %p= "Error: #{@error}" if @error.present?

app/views/home/index.haml
.wrapper.access
  .alert-bkg= render "layouts/alerts"

  #access_gate.content_block
    - if Rails.env.production?
      = render partial: "home/umich"
    - else
      = render partial: "home/public"

app/views/home/login.html.haml
.wrapper.access
  .alert-bkg= render "layouts/alerts"

  #access_gate.content_block
    = render partial: "home/public"

app/views/home/reset_password.haml
.wrapper.access
  #access_gate.content_block
    = link_to 'https://gradecraft.com/', :class => "logo" do
      = image_tag "logo.svg", :alt => "Return to GradeCraft homepage", :width => "450", :height => "100"
    %h1 Forgot Your Password?
    %p Enter the email address associated with your account, and you'll receive a link via email that will allow you to create a new password.
    = form_tag passwords_path do
      .form_elem
        = text_field_tag :email, nil, placeholder: "Your email address", autocorrect: "off", autocapitalize: "off", required: "true"
        = label_tag :email, "Email address"
      %input{name: "commit", :type => "submit", :value => "Request a password reset", class: "button action"}

app/views/home/style_guide.html.haml
.content_block
  %h1 Hello and welcome! I’m H1, the highest-level header
  %p
    This page will (style) guide you through the most-used components we’ll have. For instance, right now, you’re in a
    %b
      paragraph HAML tag&mdash;specifically a BOLD snippet.
    You can also get the bold by
    %strong
      using the STRONG HAML.
    So, that’s rather spiffy, and neat, and we’ll probably use this lots because we’ve got lots to show our users, instructors and students alike, what GradeCraft can do!
  %p
    Let’s see what another paragraph block looks like, following our first paragraph.
    %b
      We already know what bold looks like,
      %i
        so let’s also test out how italic looks, nested within the bold.
    It looks pretty snazzy!
    %em
      And how does ITALIC on its own look like?
    Also looking rather handsome. Plus, we can nest either italics within bold or
    %i
      %strong
        bold within italics.
    We’re set up in our SASSy CSS to handle both.

  %h2 Waddup, I’m a secondary header, an H2!
  %p
    In this paragraph block, let’s explore our numeral characters. 0 1 2 3 4 5 6 7 8 9 is how they look without any other tags or styling. Proxima Nova only has tabbular, or lined, numerals.

  %h3 But what if, you use this tertiary header, or H3, and also want numeral characters 0 1 2 3 4 5 6 7 8 9?
  %p
    As you can see, Klinic Slab, the lovely serif typeface we’re using for our headings, has old style numerals by default. These are great for when you want your numbers to blend with your letterforms better. However, what if we want tabbular, or lining, figures for our numerals?

  %h3.lining_figures So here, we’ll try 0 1 2 3 4 5 6 7 8 9 with H3.lining_figures
  %p
    As you can hopefully see, now the baselines and heights of our numeric figures are aligned&mdash;there is no longer the appearance of numerals having ascenders and descenders! How magical! If you simply add the class="lining_figures" to your element, it should align your numbers for you.

  %h4 If you want to do an inline heading, use an H4
  %p
    With text underneath, in a paragraph tag, it will look like this. With text underneath, in a paragraph tag, it will look like this. With text underneath, in a paragraph tag, it will look like this.

  %h2 It’s Button Time
  %p
    So now let’s make some sample buttons, that will look like how we want and you can even click them, but they will take you nowhere.
    Let’s also examine
    %a what an inline link
    looks like, while we’re here.

  %button Standard button
  %a.button(tabindex=0) Anchor tag button
  %button.secondary Secondary button
  %button.action Call to action button
  %button(disabled) Disabled button

  %h3 We mainly use anchor tags instead of buttons,
  %p So let’s check that the styling is matching up:
  %a.button.action(tabindex=0)
    Action anchor button
  %a.button(tabindex=0)
    Anchor button
  %a.button.secondary(tabindex=0)
    Secondary anchor button
  %a.button.disabled
    Disabled anchor button

.bg-green_mint
  %h2
    Let’s try div’s with bg colors!
  %p
    We will also see how the buttons are looking on these different background colors.
  %a.button.action(tabindex=0)
    Action anchor button
  %a.button(tabindex=0)
    Anchor button
  %a.button.secondary(tabindex=0)
    Secondary anchor button
  %a.button.disabled
    Disabled anchor button

.bg-green_lime
  %h2
    Let’s try div’s with bg colors!
  %p
    We will also see how the buttons are looking on these different background colors.
  %a.button.action(tabindex=0)
    Action anchor button
  %a.button(tabindex=0)
    Anchor button
  %a.button.secondary(tabindex=0)
    Secondary anchor button
  %a.button.disabled
    Disabled anchor button

.bg-yellow
  %h2
    Let’s try div’s with bg colors!
  %p
    We will also see how the buttons are looking on these different background colors.
  %a.button.action(tabindex=0) Action anchor button
  %a.button(tabindex=0) Anchor button
  %a.button.secondary(tabindex=0) Secondary anchor button
  %a.button.disabled Disabled anchor button

.content_block
  %p
    We also have instances where our colorful divs are highlighted, or at least their headings are called out more. So now we’ll also build that and see how it looks.

.bg-green_mint.highlight
  %h2
    Highlighted Heading Right Here
  %p
    Then there’s some text chillin’ out here. Then there’s some text chillin’ out here. Then there’s some text chillin’ out here.

.content_block
  %h2 Form Elements
  %p Let’s see how our form elements are looking! Below are example inputs (type=email, and type=text) that are also unrequired and required.
  .form_elem
    %input{"type"=>"email", "id"=>"user_email", "placeholder"=>"Please enter your email", "required"=>"true"}
    %label{"for"=>"user_email"} My email address
  .form_elem
    %input{"type"=>"text", "id"=>"test_text_input", "placeholder"=>"This is a test text input"}
    %label{"for"=>"test_text_input"} Test text input
  .form_elem
    %textarea{"id"=>"test_textarea", "placeholder"=>"This is a test textarea"}
    %label{"for"=>"test_textarea"} Test textarea
  .form_elem
    %textarea{"id"=>"test_textarea_required", "placeholder"=>"This is a test textarea", "required"=>"true"}
    %label{"for"=>"test_textarea-required"} Test textarea

  %p Below is an example div.button_block, to be used if you want to distance your main call-to-action button (usually a submit, which can’t be undone) from the other buttons. (But it won’t be so on small devices, where screen real estate is diminished.)
  .button_block
    %a.button Save a draft
    %a.button.secondary Cancel
    %a.button.action Submit

.bg-yellow
  %h2 Radio buttons
  %p Single selects
  .form_options
    %input{name: "test_group_radio", type: "radio", value: "radio1", id: "test_radio_1"}
    %label{for: "test_radio_1"} Single select option 1
  .form_options
    %input{name: "test_group_radio", type: "radio", value: "radio2", id: "test_radio_2"}
    %label{for: "test_radio_2"} Single select option 2
  .form_options
    %input{name: "test_group_radio", type: "radio", value: "radio3", id: "test_radio_3"}
    %label{for: "test_radio_3"} Single select option 3
  .form_options
    %input{name: "test_group_radio1", type: "radio", value: "radio4", id: "test_radio_4", disabled: "disabled"}
    %label{for: "test_radio_4"} Disabled single select option
  .form_options
    %input{name: "test_group_radio1", type: "radio", value: "radio5", id: "test_radio_5", disabled: "disabled", checked: "checked"}
    %label{for: "test_radio_5"} Disabled &amp; checked single select option

  %h2 Checkbox buttons
  %p Multiple selects
  .form_options
    %input{name: "test_group_checkbox", type: "checkbox", value: "checkbox1", id: "test_checkbox_1"}
    %label{for: "test_checkbox_1"} Multiple select option 1
  .form_options
    %input{name: "test_group_checkbox", type: "checkbox", value: "checkbox2", id: "test_checkbox_2"}
    %label{for: "test_checkbox_2"} Multiple select option 2
  .form_options
    %input{name: "test_group_checkbox", type: "checkbox", value: "checkbox3", id: "test_checkbox_3"}
    %label{for: "test_checkbox_3"} Multiple select option 3
  .form_options
    %input{name: "test_group_checkbox1", type: "checkbox", value: "checkbox4", id: "test_checkbox_4", disabled: "disabled"}
    %label{for: "test_checkbox_4"} Disabled multiple select option
  .form_options
    %input{name: "test_group_checkbox1", type: "checkbox", value: "checkbox5", id: "test_checkbox_5", disabled: "disabled", checked: "checked"}
    %label{for: "test_checkbox_5"} Disabled &amp; checked multiple select option

.content_block
  %p This is a simple form helper output for a checkbox:
  = simple_form_for User.new do |f|
    -# = f.input :first_name, label: false
    -# = f.label :first_name, :label => "FIRST NAMEEEEEEEEE"
    -# = f.input :last_name
    = f.input :admin, type: "checkbox", wrapper_html: { class: "form_options" }