config/routes.rb
require "admin_constraint"

Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Resque::Server, at: "/jobs", constraints: AdminConstraint.new
  mount JasmineRails::Engine, at: '/specs', constraints: AdminConstraint.new if defined?(JasmineRails)

  # 1. Analytics & Charts
  # 2. Announcements
  # 3. Assignments, Submissions, Grades
  # 4. Assignment Types
  # 5. Badges
  # 6. Challenges
  # 7. Integrations
  # 8. Courses
  # 9. Groups
  # 10. Informational Pages
  # 11. Grade Schemes
  # 12. Teams
  # 13. Users
  # 14. User Auth
  # 15. Uploads
  # 16. Events
  # 17. Attendance
  # 18. API Calls
  # 19. Exports
  # 20. Learning Objectives
  # 21. Errors
  # 22. Admin

  # 1. Analytics & Charts
  namespace :analytics do
    get :staff
    get :students
    get :all_events
    get :login_events
    get :login_role_events
    get :role_events
    get :all_pageview_events
    get :all_role_pageview_events
    get :all_user_pageview_events
    get :pageview_events
    get :role_pageview_events
    get :user_pageview_events
  end

  post "analytics_events/predictor_event"
  post "analytics_events/tab_select_event"

  # 2. Announcements
  resources :announcements, except: [:edit, :update]

  # 3. Assignments, Submissions, Grades
  namespace :assignments do
    resources :importers, param: :provider_id, only: [:index, :show] do
      get :assignments
      get :download
      post "/courses/:id/assignments/import", action: :assignments_import,
        as: :assignments_import
      post "/assignments/:id/refresh", action: :refresh_assignment, as: :refresh_assignment
      post "/assignments/:id/update", action: :update_assignment, as: :update_assignment
    end
  end

  resources :assignments, except: [:create, :update]  do
    collection do
      get :feed
      get :settings
      post "copy", to: "assignments#copy"
      get "export_structure"
    end

    member do
      get "grades_review"
    end

    # routes for all grades that are associated with an assignment
    # single resources should go directly on the grades controller
    resources :grades, only: [:index], module: :assignments do
      collection do
        get :export
        get :export_earned_levels
        get :mass_edit
        put :mass_update
        post :self_log
        delete :delete_self_logged
        delete :delete_all
      end
    end

    resource :groups, only: [], module: :assignments do
      resources :grades, only: [], module: :groups do
        collection do
          get :mass_edit
          put :mass_update
        end
      end
    end

    namespace :grades do
      resources :importers, param: :provider_id, only: [:index, :show] do
        get :download
        post :upload
        get :assignments
        get "/courses/:id/grades", action: :grades, as: :grades
        post "/courses/:id/grades/import", action: :grades_import, as: :grades_import
      end
    end

    resources :groups, only: [], module: :assignments do
      get :grade, on: :member
    end

    resources :students, only: [], module: :assignments do
      post :grade
    end

    resources :submissions, except: :index

    resource :rubrics, only: :destroy do
      get :index_for_copy, on: :collection
      post :copy, on: :collection
      get :export, on: :collection
    end
  end

  resources :grades, only: [:show, :destroy, :edit] do
    member do
      post :exclude
      post :feedback_read
      post :include
    end
    collection do
      put :release
    end
  end

  resources :submission_files, only: [] do
    get :download
  end

  resources :unlock_states, only: [:create, :destroy, :update] do
    member do
      post :manually_unlock
    end
  end
  resources :unlock_conditions, only: [:create, :destroy, :update]

  resources :levels, only: [:create, :destroy, :update]

  # 4. Assignment Types
  resources :assignment_types, except: [:show] do
    get :all_grades, on: :member
    get :export_scores, on: :member
    get :export_all_scores, on: :collection
  end

  # 5. Badges
  resources :badges, except: [:update, :create] do
    get "export_structure", on: :collection
    resources :earned_badges do
      get :mass_edit, on: :collection
      post :mass_earn, on: :collection
    end
    namespace :badges do
      resources :importers, param: :provider_id, only: [:index, :show] do
        get :download
        post :upload
      end
    end
  end

  # 6. Challenges
  resources :challenges do
    resources :challenge_grades, only: [:new, :create], module: :challenges do
      collection do
        put :release
        get :mass_edit
        put :mass_update
      end
    end
  end

  resources :challenge_grades, except: [:index, :new, :create]

  # 7. Integrations
  resources :integrations, only: [:create, :index] do
    collection do
      resource :google, controller: :google, only: [], module: :integrations do
        collection do
          get :new_user
          get :confirm_instructor_role
        end
      end
    end
    resources :courses, only: [:create, :destroy], module: :integrations
  end

  namespace :google_calendars, only: [] do
    resources :assignments, only: [ ] do
      collection do
        post "assignment/:id", action: :add_assignment, as: :add_assignment
        post "/all_assignments", action: :add_assignments, as: :add_assignments
      end
    end
    resources :events do
      collection do
        post "event/:id", action: :add_event, as: :add_event
        post "/all_events", action: :add_events, as: :add_events
      end
    end
  end

  # 8. Courses
  resources :courses, except: [:show] do
    post :copy, on: :collection
    post :recalculate_student_scores, on: :member
    put :publish, on: :member
    put :unpublish, on: :member
    post :activate_all_students, on: :collection
    get :badges, on: :member
    get :change, on: :member
    get :new_external, on: :collection
    post :create_external, on: :collection
    get :overview, on: :collection
    get :edit_dashboard_message, on: :collection
    put :update_dashboard_message, on: :collection

    resources :multipliers, only: [] do
      get :export, on: :collection
    end
  end

  resources :course_memberships, only: [:index, :create, :delete, :destroy] do
    collection do
      delete :delete_many
    end
    member do
      put :deactivate
      put :reactivate
    end
  end

  # 9. Groups
  resources :groups

  # 10. Informational Pages
  controller :info do
    get :dashboard
    get :predictor
    get :earned_badges
    get :export_earned_badges
    get :final_grades
    get :gradebook
    get :learning_objectives_outcomes_file
    get :submissions
    get :grading_status
    get :gradebook_file
    get :multiplied_gradebook
    get :multiplier_choices
    get :per_assign
    get :research_gradebook
    get :syllabus
  end

  controller :home do
    get :login
    get :reset_password
    get :health_check
    get :style_guide, constraints: AdminConstraint.new
  end

  # 11. Grade Schemes
  resources :grade_scheme_elements, only: [:index, :edit, :update] do
    collection do
      get :mass_edit
      get :export_structure
    end
  end

  # 12. Teams
  resources :teams

  # 13. Users
  %w{students gsis professors admins}.each do |role|
    get "users/#{role}/new", to: "users#new", as: "new_#{role.singularize}",
      role: role.singularize
  end

  resources :users, except: :show do
    member do
      get :activate
      get :activate_set_password
      get :resend_activation_email
      put :manually_activate
      post :activate_set_password, action: :activated
      post :activate, action: :activated_external
      post :flag
    end
    collection do
      get :edit_profile
      put :update_profile
      get :import
      get :search
      post :upload
      get :new_external
      get :new_external_google
      post :create_external
    end
  end

  namespace :users do
    resources :importers, only: :index, param: :provider_id do
      get :users
      get :download
      post "/course/:id/users/import", action: :users_import, as: :users_import
    end
  end

  resources :students, only: [:index, :show] do
    resources :badges, only: [:index, :show], module: :students
    resources :assignment_type_weights, only: [:index], module: :students
    member do
      get :recalculate
    end
  end

  resources :staff, only: [:index, :show]

  resources :observers, only: :index

  # 14. User Auth
  post "auth/lti/callback", to: "user_sessions#lti_create"
  get "auth/google_oauth2/callback", to: "integrations/google#auth_callback"
  get "/auth/:provider/callback", to: "authorizations#create", as: :create_authorization
  get "auth/failure", to: "application#failed_authentication", as: :auth_failure

  # Canvas OmniAuth setup
  match "/auth/canvas/setup", to: "canvas_session#new", via: [:get, :post]

  get :logout, to: "user_sessions#destroy", as: :logout
  resources :user_sessions, only: [:create, :destroy, :student] do
    collection do
      get :instructors
    end
  end
  resources :passwords, except: [:new, :destroy, :index, :show]

  get "impersonate_student/:student_id", to: "user_sessions#impersonate_student", as: :student_preview
  get "exit_student_impersonation", to: "user_sessions#exit_student_impersonation"

  # SAML
  get "saml/init"
  post "saml/consume"
  get "saml/metadata"
  get "saml/logout"

  get "lti/:provider/launch", to: "lti#launch", as: :launch_lti_provider

  # Google Auth
  post "google/launch_from_activation_token/users/:id", to: "google#launch_from_activation_token", as: :launch_from_activation_token_google
  post "google/launch_from_login/", to: "google#launch_from_login", as: :launch_from_login_google

  # 15. Uploads
  resource :uploads, only: [] do
    get :remove
  end

  # 16. Events
  resources :events do
    post :copy, on: :collection
  end

  resources :canvas_session, only: [:index, :new]

app/controllers/info_controller.rb
class InfoController < ApplicationController
  include GradesHelper
  include SubmissionsHelper

  helper_method :sort_column, :sort_direction, :predictions

  before_action :ensure_not_observer?, except: [:predictor, :syllabus]
  before_action :ensure_staff?, except: [:dashboard, :predictor, :syllabus]
  before_action :find_team,
    only: [:earned_badges, :multiplier_choices]
  before_action :find_students,
    only: [:earned_badges, :multiplier_choices, :final_grades_for_course ]
  before_action :use_current_course, only: [:earned_badges, :per_assign, :multiplier_choices, :gradebook]
  before_action :ensure_current_course_role?, only: :dashboard

  # Displays student and instructor dashboard
  def dashboard
    @events = Timeline.new(current_course).events_by_due_date
    render :dashboard, Info::DashboardCoursePlannerPresenter.build({
      student: current_student,
      assignments: current_course.assignments.chronological,
      course: current_course,
      view_context: view_context
    })
  end

  def syllabus
  end

  # Display the grade predictor
  def predictor
  end

  def earned_badges
    @teams = @course.teams
    @badges = @course.badges.ordered
  end

  # Displaying ungraded submissions, and existing grades by status
  def grading_status
    @has_submissions_or_grades = ungraded_submissions_count_for(current_course).positive? ||
      in_progress_grades_count_for(current_course).positive? ||
      ready_for_release_grades_count_for(current_course).positive? ||
      resubmission_count_for(current_course).positive?
  end

  # Displaying per assignment summary outcome statistics
  def per_assign
    @assignment_types = @course.assignment_types.ordered.includes(:assignments)
  end

  def export_earned_badges
    course = Course.find_by(id: params[:id])
    respond_to do |format|
      format.csv do
        send_data EarnedBadgeExporter.new.earned_badges_for_course(course.earned_badges),
        filename: "#{course.name} Awarded #{ term_for :badges } - #{ Date.today }.csv"
      end
    end
  end

  def final_grades
    course = current_user.courses.find_by(id: params[:id])
    respond_to do |format|
      format.csv do
        send_data CourseGradeExporter.new.final_grades_for_course(course),
        filename: "#{ course.name } Final Grades - #{ Date.today }.csv"
      end
    end
  end

  def gradebook
  end

  def learning_objectives_outcomes_file
    course = current_user.courses.find_by(id: params[:id])
    LearningObjectivesOutcomesExporterJob
      .new(
        user_id: current_user.id,
        course_id: course.id,
        filename: "#{ course.name } Learning Objectives Outcomes - #{ Date.today }.csv"
      ).enqueue
      
    flash[:notice]="Your request to export the learning objectives outcomes for \"#{ course.name }\" is currently being processed. We will email you the data shortly."
    redirect_back_or_default
  end

  def gradebook_file
    course = current_user.courses.find_by(id: params[:id])
    GradebookExporterJob
      .new(
        user_id: current_user.id,
        course_id: course.id,
        filename: "#{ course.name } Gradebook - #{ Date.today }.csv"
      ).enqueue

    flash[:notice]="Your request to export the gradebook for \"#{ course.name }\" is currently being processed. We will email you the data shortly."
    redirect_back_or_default
  end

  def multiplied_gradebook
    course = current_user.courses.find_by(id: params[:id])
    MultipliedGradebookExporterJob
      .new(user_id: current_user.id, course_id: course.id, filename: "#{ course.name } Multiplied Gradebook - #{ Date.today }.csv").enqueue

    flash[:notice]="Your request to export the multiplied gradebook for \"#{ course.name }\" is currently being processed. We will email you the data shortly."
    redirect_back_or_default
  end

  # downloadable grades for course with  export
  def research_gradebook
    course = current_user.courses.find_by(id: params[:id])
    @grade_export_job = GradeExportJob.new(user_id: current_user.id, course_id: course.id,
    filename: "#{ course.name } Research Gradebook - #{ Date.today }.csv")
    @grade_export_job.enqueue

    flash[:notice]="Your request to export grade data from course \"#{ course.name }\" is currently being processed. We will email you the data shortly."
    redirect_back_or_default
  end

  # Chart displaying all of the student weighting choices thus far
  def multiplier_choices
    @assignment_types = current_course.assignment_types.ordered
    @teams = current_course.teams
  end

  def submissions
    course = current_user.courses.find_by(id: params[:id])
    @submission_export_job = SubmissionExportJob.new(user_id: current_user.id, course_id: course.id, filename: "#{ course.name } Submissions Export - #{ Date.today }.csv")
    @submission_export_job.enqueue

    flash[:notice]="Your request to export submissions from course \"#{ course.name }\" is currently being processed. We will email you the data shortly."
    redirect_back_or_default
  end

  private

  def find_team
    @team = current_course.teams.find_by(id: params[:team_id]) if params[:team_id]
  end

  def find_students
    if @team
      @students = current_course.students_being_graded_by_team(@team).order_by_name
    else
      @students = current_course.students_being_graded.order_by_name
    end
  end

  def ensure_current_course_role?
    if current_user.role(current_course).nil?
      next_course = current_user.course_memberships.first.try(:course)
      return redirect_to change_course_path(next_course) unless next_course.nil?
      redirect_to errors_path status_code: 401, error_type: "without_course_membership"
    end
  end
end

app/helpers/info_helper.rb
module InfoHelper
  def any_one_assignment_has_two_submissions?(assignment_types)
    assignment_types.each do |assignment_type|
      if assignment_type.assignments.select {|a| a.grades.student_visible.length > 1}.present?
        return true
      end
    end    
    return false
  end
end

app/views/info/_staff_onboarding.html.haml
.modal-overlay#modal-window{'aria-hidden': 'true', role: 'dialog', 'aria-label': 'Staff Onboarding', 'data-first-load': current_user.course_memberships.where(course: current_course).first.has_seen_course_onboarding? ? 'false' : 'true' }
  .modal-wrapper.modal-content#modal-holder{role: "document"}
    .modal-slider.onboarding-slides
      = render partial: "info/staff_onboarding/staff_onboarding_slide1"
      = render partial: "info/staff_onboarding/staff_onboarding_slide2"
      = render partial: "info/staff_onboarding/staff_onboarding_slide3"
      = render partial: "info/staff_onboarding/staff_onboarding_slide4"
      = render partial: "info/staff_onboarding/staff_onboarding_slide5"
      = render partial: "info/staff_onboarding/staff_onboarding_slide6"

    %button.btn-close#modal-close{type: 'submit', 'aria-label': 'close'}= glyph(:times)

app/views/info/_student_onboarding.html.haml
.modal-overlay#modal-window{'aria-hidden': 'true', role: 'dialog', 'aria-label': 'Student Onboarding', 'data-first-load': current_user.onboarded?(current_course) ? 'false' : 'true' }
  .modal-wrapper.modal-content#modal-holder{role: "document"}
    .modal-slider.onboarding-slides
      = render partial: "info/student_onboarding/student_onboarding_slide1"
      = render partial: "info/student_onboarding/student_onboarding_slide2"
      = render partial: "info/student_onboarding/student_onboarding_slide3"
      = render partial: "info/student_onboarding/student_onboarding_slide4"
      = render partial: "info/student_onboarding/student_onboarding_slide5", locals: { presenter: presenter }

      - if presenter.has_course_specific_features?
        = render partial: "info/student_onboarding/student_onboarding_slide6", locals: { presenter: presenter }

    %button.btn-close#modal-close{type: 'submit', 'aria-label': 'close'}= glyph(:times)

app/views/info/_students_table.haml
%table.dynatable.no-button-bar{role: "grid"}
  %thead
    %tr
      %th{ scope: "column", :width => "20%" }= course.student_term
      %th{ scope: "column", :width => "10%" } Score
      %th{ scope: "column", :width => "10%" } Level
      - if course.has_badges?
        %th{ scope: "column", :width => "5%" } Badges
      - if course.has_teams?
        %th{ scope: "column" }= course.team_term
        %th{ scope: "column" }= course.team_leader_term
      %th{ scope: "column", :width => "20%"  } Last Login
  %tbody
    - students.each do |student|
      %tr
        %td= link_to student.name, student_path(student)
        %td= points student.score_for_course(current_course)
        %td= points student.grade_for_course(current_course).try(:name)

        - if course.has_badges?
          %td= student.earned_badges_for_course(current_course).count

        - if course.has_teams?
          %td
            - if student.team
              = link_to student.team.name, student.team
          %td
            - if student.team && student.team.leaders.present?
              %ul
                - student.team.leaders.each do |leader|
                  - cache ["v1", leader] do
                    %li= link_to leader.first_name, staff_path(leader)
        %td= student.last_course_login(course) || "(never)"

app/views/info/_teams_table.haml
%table.dynatable
  %thead
    %tr
      %th= course.team_term
      - if current_course.challenges.present?
        %th #{ term_for :challenge } Score
      %th Average Grade
      - if current_course.has_badges?
        %th Badges
      %th= course.team_leader_term
  %tbody
    - teams.order_by_rank.each do |team|
      %tr
        %td= link_to team.name, team_path(team)
        - if current_course.challenges.present?
          %td= points team.try(:challenge_grade_score)

        %td= points team.try(:average_score)
        - if current_course.has_badges?
          %td= team.badge_count
        %td
          - if team.leaders.present?
            - team.leaders.each do |team_leader|
              = link_to team_leader.try(:name), team_leader

app/views/info/dashboard.html.haml
#dashboard-timeline= render partial: "info/dashboard/#{current_user.role(current_course)}_dashboard", locals: { presenter: presenter }

app/views/info/earned_badges.html.haml
.pageContent
  = render "layouts/alerts"

  = team_filter(@teams) if current_course.has_teams?

  .scroll-table
    .table-wrapper
      %table.dynatable.no-table-header.no-button-bar
        %caption.sr-only All Awarded Achievements
        %thead
          %tr
            %th{scope: "col"} First Name
            %th{scope: "col"} Last Name
            - @badges.each do |badge|
              %th{:scope => "col", :id => badge.try(:id), :name => badge.try(:name)}= badge.name
            - if current_course.valuable_badges?
              %th{scope: "col"} Total Badge Score
        %tbody
          - @students.each do |student|
            %tr
              %td= link_to student.first_name, student_path(student)
              %td= link_to student.last_name, student_path(student)
              - @badges.each do |badge|
                %td
                  -if student.awarded_badges_for_badge(badge.id).count > 0
                    .img-cropper.xsmall-crop.earned-badge-table-img
                      %img{:src => badge.try(:icon), :alt => badge.try(:name), :title => badge.name}
                    %span x#{student.awarded_badges_for_badge_count(badge.id)}

              - if current_course.valuable_badges?
                %td= points student.earned_badge_score_for_course(current_course)

app/views/info/gradebook.html.haml
.pageContent
  = render "layouts/alerts"

  %gradebook{"data-has-badges"=>"#{current_course.valuable_badges?}"}

app/views/info/grading_status.html.haml
.pageContent
  = render "layouts/alerts"

  .grading-status-card-wrapper
    .card.quarter
      .card-text
        .center.bold.inverse.large= ungraded_submissions_count_for(current_course)
        %h2.grading-status-name.center.inverse Ungraded Submissions

    .card.quarter
      .card-text
        .center.bold.inverse.large= in_progress_grades_count_for(current_course)
        %h2.grading-status-name.center.inverse In Progress Grades

    .card.quarter
      .card-text
        .center.bold.inverse.large= ready_for_release_grades_count_for(current_course)
        %h2.grading-status-name.center.inverse Ready For Release Grades

    .card.quarter
      .card-text
        .center.bold.inverse.large= resubmission_count_for(current_course)
        %h2.grading-status-name.center.inverse Resubmissions

  -# Search input for all four subsections
  - if @has_submissions_or_grades
    %sortable-search-input.grading-status-search-input

  -# Ungraded submissions
  - if ungraded_submissions_count_for(current_course).positive?
    %section.ungraded-submissions.collapseSection{"role"=>"tablist", "id"=>"ungraded"}
      .collapse{"role"=>"tab"}
        %a
          %h3.grading-status-header
            %i.fa.fa-chevron-circle-right.fa-fw
            Ungraded Submissions
      %grading-status-submissions{"data-course-has_teams"=>"#{current_course.has_teams?}",
                                  "data-assignment-term"=>"#{term_for :assignment}",
                                  "data-team-term"=>"#{term_for :team}",
                                  "data-links-visible"=>"#{current_user_is_admin? || current_course.active?}",
                                  "data-type"=>"Ungraded",
                                  "role"=>"tabpanel"}

  -# In progress grades
  - if in_progress_grades_count_for(current_course).positive?
    %section.in-progress-grades.collapseSection{"role"=>"tablist", "id"=>"inProgress"}
      .collapse{"role"=>"tab"}
        %a
          %h3.grading-status-header
            %i.fa.fa-chevron-circle-right.fa-fw
            In Progress Grades
      %grading-status-grades{"data-course-has_teams"=>"#{current_course.has_teams?}",
                             "data-assignment-term"=>"#{term_for :assignment}",
                             "data-team-term"=>"#{term_for :team}",
                             "data-links-visible"=>"#{current_user_is_admin? || current_course.active?}",
                             "data-type"=>"InProgress",
                             "role"=>"tabpanel"}

  -# Ready for release grades
  - if ready_for_release_grades_count_for(current_course).positive?
    %section.ready-for-release-grades.collapseSection{"role"=>"tablist", "id"=>"readyForRelease"}
      .collapse{"role"=>"tab"}
        %a
          %h3.grading-status-header
            %i.fa.fa-chevron-circle-right.fa-fw
            Ready for Release Grades
      %grading-status-grades{"data-course-has_teams"=>"#{current_course.has_teams?}",
                             "data-assignment-term"=>"#{term_for :assignment}",
                             "data-team-term"=>"#{term_for :team}",
                             "data-links-visible"=>"#{current_user_is_admin? || current_course.active?}",
                             "data-type"=>"ReadyForRelease",
                             "role"=>"tabpanel"}

  -# Resubmissions
  - if resubmission_count_for(current_course).positive?
    %section.resubmissions.collapseSection{"role"=>"tablist", "id"=>"resubmissions"}
      .collapse{"role"=>"tab", "data-collapsed-class"=>"ng-hide"}
        %a
          %h3.grading-status-header
            %i.fa.fa-chevron-circle-right.fa-fw
            Resubmissions
      %grading-status-submissions{"data-course-has_teams"=>"#{current_course.has_teams?}",
                                  "data-assignment-term"=>"#{term_for :assignment}",
                                  "data-team-term"=>"#{term_for :team}",
                                  "data-links-visible"=>"#{current_user_is_admin? || current_course.active?}",
                                  "data-type"=>"Resubmitted",
                                  "role"=>"tabpanel"}

app/views/info/multiplier_choices.html.haml
.pageContent
  = render "layouts/alerts"

  = team_filter(@teams) if current_course.has_teams?

  %table.dynatable
    %thead
      %tr
        %th First Name
        %th Last Name
        - @assignment_types.each do |assignment_type|
          - if assignment_type.student_weightable?
            %th= assignment_type.name
        %th Fully Assigned?
    %tbody
      - @students.each do |student|
        %tr
          %td= link_to student.first_name, student_path(student)
          %td= link_to student.last_name, student_path(student)
          - @assignment_types.each do |assignment_type|
            - if assignment_type.student_weightable?
              %td= student.weight_for_assignment_type(assignment_type)
          %td
            = student.weight_spent?(current_course) ? "Yes" : "No"

app/views/info/per_assign.html.haml
.pageContent
  = render "layouts/alerts"

  = render partial: "analytics/in_page_nav"

  - if @assignment_types.length == 0 || @course.assignments.length == 0
    %p
      There are currently no assignments in this course; add an assignment to see analytics.

  - if @course.assignments.length > 0 && !any_one_assignment_has_two_submissions?(@assignment_types)
    %p
      No assignment currently has more than one graded assignment visible to students; grade and release more assignments to see analytics.
  
  - @assignment_types.each do |assignment_type|
    - assignments_for_type = assignment_type.assignments
    - if assignments_for_type.select {|a| a.grades.student_visible.length > 1}.present?
      %h2.subtitle= assignment_type.name

      %table.dynatable
        %caption.sr-only= assignment_type.name
        %thead
          %tr
            %th{"scope" => "col"} Name
            %th{"scope" => "col"} Min
            %th{"scope" => "col"} Max
            %th{"scope" => "col"} Median
            %th{"scope" => "col"}
              Ave
              = tooltip("ave-tip_#{assignment_type.id}", "info-circle") do
                The average of all grades including those who earned zero
            %th{"scope" => "col"}
              Avg Earned
              = tooltip("ave-earned-tip_#{assignment_type.id}", "info-circle") do
                The average of all scores above zero
            %th{"scope" => "col"} Predicted
            %th Submissions
            %th Grades
            %th{:style => "min-width: 220px"}
        %tbody
          - assignments = assignments_for_type
          - assignments.each do |assignment|
            - if assignment.grades.student_visible.present?
              %tr
                %td= link_to assignment.name, assignment
                %td= points assignment.low_score
                %td= points assignment.high_score
                %td= points assignment.median
                %td= points assignment.average
                %td= points assignment.earned_average
                %td= points assignment.predicted_count
                %td
                  - if assignment.accepts_submissions?
                    = points assignment.submissions.submitted.count
                %th= points assignment.grade_count
                %th
                  %ul.button-bar.right
                    = active_course_link_to decorative_glyph(:check) + "Quick Grade", mass_edit_assignment_grades_path(assignment), class: "button"
                    %li= link_to decorative_glyph("cloud-download") + "Download Grades", export_assignment_grades_path(assignment, format: :csv), class: "button"

app/views/info/predictor.haml
#student-main-content
  %predictor

app/views/info/syllabus.html.haml
.pageContent
  - if current_course.meeting_times.present?
    %h3.bold Course Details
    = glyph(:bank) + current_course.meeting_times + ' ' + current_course.location
    %p

  - if current_course.gameful_philosophy.present?
    %h3.bold Grading Philosophy
    = render partial: "courses/grading_philosophy", locals: {course: current_course}
    %p

  - if current_course.course_rules.present?
    %h3.bold Course Rules
    %p= raw current_course.course_rules

  - if current_course.syllabus.present?
    %h3.bold Course Syllabus
    = external_link_to "Download the Current Syllabus", current_course.syllabus_url
    %p

  - if current_course.grade_scheme_elements.with_lowest_points.present?
    %h3.bold Grading Scheme
    - if current_user_is_student?
      = render partial: "grade_scheme_elements/index_student", locals: { "@grade_scheme_elements": current_course.grade_scheme_elements.order_by_points_desc }
    - elsif current_user_is_observer?
      = render partial: "grade_scheme_elements/index_observer", locals: { "@grade_scheme_elements": current_course.grade_scheme_elements.order_by_points_desc }
    - elsif current_user_is_staff?
      = render partial: "grade_scheme_elements/index_staff", locals: {  "@grade_scheme_elements": current_course.grade_scheme_elements.order_by_points_desc }